/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package net.loveruby.cflat.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACES = 1;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 4;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int SHORT = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int LONG = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int DOUBLE = 12;
  /** RegularExpression Id. */
  int STRUCT = 13;
  /** RegularExpression Id. */
  int UNION = 14;
  /** RegularExpression Id. */
  int ENUM = 15;
  /** RegularExpression Id. */
  int STATIC = 16;
  /** RegularExpression Id. */
  int EXTERN = 17;
  /** RegularExpression Id. */
  int CONST = 18;
  /** RegularExpression Id. */
  int VOLATILE = 19;
  /** RegularExpression Id. */
  int SIGNED = 20;
  /** RegularExpression Id. */
  int UNSIGNED = 21;
  /** RegularExpression Id. */
  int BOOL_ = 22;
  /** RegularExpression Id. */
  int INLINE = 23;
  /** RegularExpression Id. */
  int RESTRICT = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int SWITCH = 27;
  /** RegularExpression Id. */
  int CASE = 28;
  /** RegularExpression Id. */
  int DEFAULT_ = 29;
  /** RegularExpression Id. */
  int WHILE = 30;
  /** RegularExpression Id. */
  int DO = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int RETURN = 33;
  /** RegularExpression Id. */
  int BREAK = 34;
  /** RegularExpression Id. */
  int CONTINUE = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int TYPEDEF = 37;
  /** RegularExpression Id. */
  int SIZEOF = 38;
  /** RegularExpression Id. */
  int IDENTIFIER = 39;
  /** RegularExpression Id. */
  int INTEGER = 40;
  /** RegularExpression Id. */
  int INTSUFFIX = 41;
  /** RegularExpression Id. */
  int LSUFFIX = 42;
  /** RegularExpression Id. */
  int FLOATLIT = 43;
  /** RegularExpression Id. */
  int EXPONENT = 44;
  /** RegularExpression Id. */
  int HEXEXPONENT = 45;
  /** RegularExpression Id. */
  int CHARACTER = 50;
  /** RegularExpression Id. */
  int STRING = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 1;
  /** Lexical state. */
  int IN_CHARACTER = 2;
  /** Lexical state. */
  int CHARACTER_TERM = 3;
  /** Lexical state. */
  int IN_STRING = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACES>",
    "\"/*\"",
    "<token of kind 3>",
    "\"*/\"",
    "<LINE_COMMENT>",
    "\"void\"",
    "\"char\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"struct\"",
    "\"union\"",
    "\"enum\"",
    "\"static\"",
    "\"extern\"",
    "\"const\"",
    "\"volatile\"",
    "\"signed\"",
    "\"unsigned\"",
    "\"_Bool\"",
    "\"inline\"",
    "\"restrict\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"goto\"",
    "\"typedef\"",
    "\"sizeof\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<INTSUFFIX>",
    "<LSUFFIX>",
    "<FLOATLIT>",
    "<EXPONENT>",
    "<HEXEXPONENT>",
    "\"\\\'\"",
    "<token of kind 47>",
    "<token of kind 48>",
    "<token of kind 49>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<token of kind 52>",
    "<token of kind 53>",
    "<token of kind 54>",
    "\"\\\"\"",
    "\"(\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"*\"",
    "\"...\"",
    "\":\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"~\"",
    "\"->\"",
  };

}
